//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALRC.Creator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALRC.Creator.Localization.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_PlayController_Open.
        /// </summary>
        public static string Btn_PlayController_Open {
            get {
                return ResourceManager.GetString("Btn_PlayController_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_PlayController.
        /// </summary>
        public static string Btn_PlayController_Play {
            get {
                return ResourceManager.GetString("Btn_PlayController_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_Add.
        /// </summary>
        public static string Btn_SongLines_Add {
            get {
                return ResourceManager.GetString("Btn_SongLines_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_End.
        /// </summary>
        public static string Btn_SongLines_End {
            get {
                return ResourceManager.GetString("Btn_SongLines_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_NextLine.
        /// </summary>
        public static string Btn_SongLines_NextLine {
            get {
                return ResourceManager.GetString("Btn_SongLines_NextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_PlayStatus.
        /// </summary>
        public static string Btn_SongLines_PlayStatus {
            get {
                return ResourceManager.GetString("Btn_SongLines_PlayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_PreviousLine.
        /// </summary>
        public static string Btn_SongLines_PreviousLine {
            get {
                return ResourceManager.GetString("Btn_SongLines_PreviousLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_QuickAdd.
        /// </summary>
        public static string Btn_SongLines_QuickAdd {
            get {
                return ResourceManager.GetString("Btn_SongLines_QuickAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_Remove.
        /// </summary>
        public static string Btn_SongLines_Remove {
            get {
                return ResourceManager.GetString("Btn_SongLines_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_SeekBackward.
        /// </summary>
        public static string Btn_SongLines_SeekBackward {
            get {
                return ResourceManager.GetString("Btn_SongLines_SeekBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_SeekForward.
        /// </summary>
        public static string Btn_SongLines_SeekForward {
            get {
                return ResourceManager.GetString("Btn_SongLines_SeekForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_SongLines_Start.
        /// </summary>
        public static string Btn_SongLines_Start {
            get {
                return ResourceManager.GetString("Btn_SongLines_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_StylesEdit_Add.
        /// </summary>
        public static string Btn_StylesEdit_Add {
            get {
                return ResourceManager.GetString("Btn_StylesEdit_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_StylesEdit_Remove.
        /// </summary>
        public static string Btn_StylesEdit_Remove {
            get {
                return ResourceManager.GetString("Btn_StylesEdit_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_WordEdit_Line_Align.
        /// </summary>
        public static string Btn_WordEdit_Line_Align {
            get {
                return ResourceManager.GetString("Btn_WordEdit_Line_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Btn_WordEdit_ParseAll.
        /// </summary>
        public static string Btn_WordEdit_ParseAll {
            get {
                return ResourceManager.GetString("Btn_WordEdit_ParseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Constant_0 {
            get {
                return ResourceManager.GetString("Constant_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Constant_1 {
            get {
                return ResourceManager.GetString("Constant_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Constant_2 {
            get {
                return ResourceManager.GetString("Constant_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_EndTime.
        /// </summary>
        public static string LineEditing_EndTime {
            get {
                return ResourceManager.GetString("LineEditing_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Comment.
        /// </summary>
        public static string LineEditing_Line_Comment {
            get {
                return ResourceManager.GetString("LineEditing_Line_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_End.
        /// </summary>
        public static string LineEditing_Line_End {
            get {
                return ResourceManager.GetString("LineEditing_Line_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_LineId.
        /// </summary>
        public static string LineEditing_Line_LineId {
            get {
                return ResourceManager.GetString("LineEditing_Line_LineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_ParentLineId.
        /// </summary>
        public static string LineEditing_Line_ParentLineId {
            get {
                return ResourceManager.GetString("LineEditing_Line_ParentLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Start.
        /// </summary>
        public static string LineEditing_Line_Start {
            get {
                return ResourceManager.GetString("LineEditing_Line_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Style.
        /// </summary>
        public static string LineEditing_Line_Style {
            get {
                return ResourceManager.GetString("LineEditing_Line_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Text.
        /// </summary>
        public static string LineEditing_Line_Text {
            get {
                return ResourceManager.GetString("LineEditing_Line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Translation.
        /// </summary>
        public static string LineEditing_Line_Translation {
            get {
                return ResourceManager.GetString("LineEditing_Line_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Transliteration.
        /// </summary>
        public static string LineEditing_Line_Transliteration {
            get {
                return ResourceManager.GetString("LineEditing_Line_Transliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Type.
        /// </summary>
        public static string LineEditing_Line_Type {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Type_Empty.
        /// </summary>
        public static string LineEditing_Line_Type_Empty {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Type_PureText.
        /// </summary>
        public static string LineEditing_Line_Type_PureText {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type_PureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Line_Type_Words.
        /// </summary>
        public static string LineEditing_Line_Type_Words {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_StartTime.
        /// </summary>
        public static string LineEditing_StartTime {
            get {
                return ResourceManager.GetString("LineEditing_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineEditing_Timeline_HintLabel.
        /// </summary>
        public static string LineEditing_Timeline_HintLabel {
            get {
                return ResourceManager.GetString("LineEditing_Timeline_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinesEdit_Line_Translation_Content.
        /// </summary>
        public static string LinesEdit_Line_Translation_Content {
            get {
                return ResourceManager.GetString("LinesEdit_Line_Translation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LinesEdit_Line_Translation_Language.
        /// </summary>
        public static string LinesEdit_Line_Translation_Language {
            get {
                return ResourceManager.GetString("LinesEdit_Line_Translation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Author.
        /// </summary>
        public static string LyricInfo_Author {
            get {
                return ResourceManager.GetString("LyricInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Duration.
        /// </summary>
        public static string LyricInfo_Duration {
            get {
                return ResourceManager.GetString("LyricInfo_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Language.
        /// </summary>
        public static string LyricInfo_Language {
            get {
                return ResourceManager.GetString("LyricInfo_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Offset.
        /// </summary>
        public static string LyricInfo_Offset {
            get {
                return ResourceManager.GetString("LyricInfo_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Proofread.
        /// </summary>
        public static string LyricInfo_Proofread {
            get {
                return ResourceManager.GetString("LyricInfo_Proofread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Timeline.
        /// </summary>
        public static string LyricInfo_Timeline {
            get {
                return ResourceManager.GetString("LyricInfo_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Translation.
        /// </summary>
        public static string LyricInfo_Translation {
            get {
                return ResourceManager.GetString("LyricInfo_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LyricInfo_Transliteration.
        /// </summary>
        public static string LyricInfo_Transliteration {
            get {
                return ResourceManager.GetString("LyricInfo_Transliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Convert.
        /// </summary>
        public static string Nav_Convert {
            get {
                return ResourceManager.GetString("Nav_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Home.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_LyricInfo.
        /// </summary>
        public static string Nav_Info {
            get {
                return ResourceManager.GetString("Nav_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_LinesEdit.
        /// </summary>
        public static string Nav_LinesEdit {
            get {
                return ResourceManager.GetString("Nav_LinesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Preview.
        /// </summary>
        public static string Nav_Preview {
            get {
                return ResourceManager.GetString("Nav_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Save.
        /// </summary>
        public static string Nav_Save {
            get {
                return ResourceManager.GetString("Nav_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_Settings.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_StylesEditing.
        /// </summary>
        public static string Nav_StylesEditing {
            get {
                return ResourceManager.GetString("Nav_StylesEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nav_WordEdit.
        /// </summary>
        public static string Nav_WordEdit {
            get {
                return ResourceManager.GetString("Nav_WordEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongInfo_Param.
        /// </summary>
        public static string SongInfo_Param {
            get {
                return ResourceManager.GetString("SongInfo_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SongInfo_Value.
        /// </summary>
        public static string SongInfo_Value {
            get {
                return ResourceManager.GetString("SongInfo_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Color.
        /// </summary>
        public static string StyleEdit_Style_Color {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Hidden.
        /// </summary>
        public static string StyleEdit_Style_Hidden {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Id.
        /// </summary>
        public static string StyleEdit_Style_Id {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Position.
        /// </summary>
        public static string StyleEdit_Style_Position {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Position_Center.
        /// </summary>
        public static string StyleEdit_Style_Position_Center {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Position_Left.
        /// </summary>
        public static string StyleEdit_Style_Position_Left {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Position_Right.
        /// </summary>
        public static string StyleEdit_Style_Position_Right {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Position_Undefined.
        /// </summary>
        public static string StyleEdit_Style_Position_Undefined {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Preview.
        /// </summary>
        public static string StyleEdit_Style_Preview {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Type.
        /// </summary>
        public static string StyleEdit_Style_Type {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Type_Background.
        /// </summary>
        public static string StyleEdit_Style_Type_Background {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Type_Normal.
        /// </summary>
        public static string StyleEdit_Style_Type_Normal {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Type_Stressed.
        /// </summary>
        public static string StyleEdit_Style_Type_Stressed {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Stressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StyleEdit_Style_Type_Whisper.
        /// </summary>
        public static string StyleEdit_Style_Type_Whisper {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title_LyricInfo.
        /// </summary>
        public static string Title_LyricInfo {
            get {
                return ResourceManager.GetString("Title_LyricInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title_SongInfo.
        /// </summary>
        public static string Title_SongInfo {
            get {
                return ResourceManager.GetString("Title_SongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle_SongLines_PreviewMode.
        /// </summary>
        public static string Toggle_SongLines_PreviewMode {
            get {
                return ResourceManager.GetString("Toggle_SongLines_PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordEdit_LyricLine_Hint_Empty.
        /// </summary>
        public static string WordEdit_LyricLine_Hint_Empty {
            get {
                return ResourceManager.GetString("WordEdit_LyricLine_Hint_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordEdit_LyricLine_Hint_PureText.
        /// </summary>
        public static string WordEdit_LyricLine_Hint_PureText {
            get {
                return ResourceManager.GetString("WordEdit_LyricLine_Hint_PureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WordEdit_LyricLines_Hint.
        /// </summary>
        public static string WordEdit_LyricLines_Hint {
            get {
                return ResourceManager.GetString("WordEdit_LyricLines_Hint", resourceCulture);
            }
        }
    }
}
