//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALRC.Creator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ALRC.Creator.Localization.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 打开.
        /// </summary>
        public static string Btn_PlayController_Open {
            get {
                return ResourceManager.GetString("Btn_PlayController_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播放 / 暂停.
        /// </summary>
        public static string Btn_PlayController_Play {
            get {
                return ResourceManager.GetString("Btn_PlayController_Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加一行.
        /// </summary>
        public static string Btn_SongLines_Add {
            get {
                return ResourceManager.GetString("Btn_SongLines_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置终点  (Num6 / D).
        /// </summary>
        public static string Btn_SongLines_End {
            get {
                return ResourceManager.GetString("Btn_SongLines_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 下一行  (Num2 / LCtrl).
        /// </summary>
        public static string Btn_SongLines_NextLine {
            get {
                return ResourceManager.GetString("Btn_SongLines_NextLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 播放 / 暂停  (Num5 / S).
        /// </summary>
        public static string Btn_SongLines_PlayStatus {
            get {
                return ResourceManager.GetString("Btn_SongLines_PlayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 上一行  (Num8 / LShift).
        /// </summary>
        public static string Btn_SongLines_PreviousLine {
            get {
                return ResourceManager.GetString("Btn_SongLines_PreviousLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 快速添加.
        /// </summary>
        public static string Btn_SongLines_QuickAdd {
            get {
                return ResourceManager.GetString("Btn_SongLines_QuickAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除此行.
        /// </summary>
        public static string Btn_SongLines_Remove {
            get {
                return ResourceManager.GetString("Btn_SongLines_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 后退 5 秒  (Num1 / Q).
        /// </summary>
        public static string Btn_SongLines_SeekBackward {
            get {
                return ResourceManager.GetString("Btn_SongLines_SeekBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 前进 5 秒  (Num3 / E).
        /// </summary>
        public static string Btn_SongLines_SeekForward {
            get {
                return ResourceManager.GetString("Btn_SongLines_SeekForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置起点  (Num4 / A).
        /// </summary>
        public static string Btn_SongLines_Start {
            get {
                return ResourceManager.GetString("Btn_SongLines_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 添加样式.
        /// </summary>
        public static string Btn_StylesEdit_Add {
            get {
                return ResourceManager.GetString("Btn_StylesEdit_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除样式.
        /// </summary>
        public static string Btn_StylesEdit_Remove {
            get {
                return ResourceManager.GetString("Btn_StylesEdit_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行对齐.
        /// </summary>
        public static string Btn_WordEdit_Line_Align {
            get {
                return ResourceManager.GetString("Btn_WordEdit_Line_Align", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动解析全部.
        /// </summary>
        public static string Btn_WordEdit_ParseAll {
            get {
                return ResourceManager.GetString("Btn_WordEdit_ParseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Constant_0 {
            get {
                return ResourceManager.GetString("Constant_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string Constant_1 {
            get {
                return ResourceManager.GetString("Constant_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        public static string Constant_2 {
            get {
                return ResourceManager.GetString("Constant_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 结束时间.
        /// </summary>
        public static string LineEditing_EndTime {
            get {
                return ResourceManager.GetString("LineEditing_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 评论.
        /// </summary>
        public static string LineEditing_Line_Comment {
            get {
                return ResourceManager.GetString("LineEditing_Line_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 终止时间.
        /// </summary>
        public static string LineEditing_Line_End {
            get {
                return ResourceManager.GetString("LineEditing_Line_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行 ID.
        /// </summary>
        public static string LineEditing_Line_LineId {
            get {
                return ResourceManager.GetString("LineEditing_Line_LineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 父行 ID.
        /// </summary>
        public static string LineEditing_Line_ParentLineId {
            get {
                return ResourceManager.GetString("LineEditing_Line_ParentLineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 起始时间.
        /// </summary>
        public static string LineEditing_Line_Start {
            get {
                return ResourceManager.GetString("LineEditing_Line_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式.
        /// </summary>
        public static string LineEditing_Line_Style {
            get {
                return ResourceManager.GetString("LineEditing_Line_Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文本内容.
        /// </summary>
        public static string LineEditing_Line_Text {
            get {
                return ResourceManager.GetString("LineEditing_Line_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻译.
        /// </summary>
        public static string LineEditing_Line_Translation {
            get {
                return ResourceManager.GetString("LineEditing_Line_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音译.
        /// </summary>
        public static string LineEditing_Line_Transliteration {
            get {
                return ResourceManager.GetString("LineEditing_Line_Transliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        public static string LineEditing_Line_Type {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 伴奏.
        /// </summary>
        public static string LineEditing_Line_Type_Empty {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 纯文本.
        /// </summary>
        public static string LineEditing_Line_Type_PureText {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type_PureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逐字.
        /// </summary>
        public static string LineEditing_Line_Type_Words {
            get {
                return ResourceManager.GetString("LineEditing_Line_Type_Words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 开始时间.
        /// </summary>
        public static string LineEditing_StartTime {
            get {
                return ResourceManager.GetString("LineEditing_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 聚焦到下方文本框即可进行打轴.
        /// </summary>
        public static string LineEditing_Timeline_HintLabel {
            get {
                return ResourceManager.GetString("LineEditing_Timeline_HintLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string LinesEdit_Line_Translation_Content {
            get {
                return ResourceManager.GetString("LinesEdit_Line_Translation_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        public static string LinesEdit_Line_Translation_Language {
            get {
                return ResourceManager.GetString("LinesEdit_Line_Translation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        public static string LyricInfo_Author {
            get {
                return ResourceManager.GetString("LyricInfo_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时长.
        /// </summary>
        public static string LyricInfo_Duration {
            get {
                return ResourceManager.GetString("LyricInfo_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言 (RFC 1766).
        /// </summary>
        public static string LyricInfo_Language {
            get {
                return ResourceManager.GetString("LyricInfo_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 偏移 (对歌曲快几毫秒).
        /// </summary>
        public static string LyricInfo_Offset {
            get {
                return ResourceManager.GetString("LyricInfo_Offset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 校对.
        /// </summary>
        public static string LyricInfo_Proofread {
            get {
                return ResourceManager.GetString("LyricInfo_Proofread", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时轴.
        /// </summary>
        public static string LyricInfo_Timeline {
            get {
                return ResourceManager.GetString("LyricInfo_Timeline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 翻译.
        /// </summary>
        public static string LyricInfo_Translation {
            get {
                return ResourceManager.GetString("LyricInfo_Translation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 音译.
        /// </summary>
        public static string LyricInfo_Transliteration {
            get {
                return ResourceManager.GetString("LyricInfo_Transliteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 转换.
        /// </summary>
        public static string Nav_Convert {
            get {
                return ResourceManager.GetString("Nav_Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 主页.
        /// </summary>
        public static string Nav_Home {
            get {
                return ResourceManager.GetString("Nav_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 信息.
        /// </summary>
        public static string Nav_Info {
            get {
                return ResourceManager.GetString("Nav_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 行编辑.
        /// </summary>
        public static string Nav_LinesEdit {
            get {
                return ResourceManager.GetString("Nav_LinesEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览.
        /// </summary>
        public static string Nav_Preview {
            get {
                return ResourceManager.GetString("Nav_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 工程.
        /// </summary>
        public static string Nav_Save {
            get {
                return ResourceManager.GetString("Nav_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 设置.
        /// </summary>
        public static string Nav_Settings {
            get {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式编辑.
        /// </summary>
        public static string Nav_StylesEditing {
            get {
                return ResourceManager.GetString("Nav_StylesEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 逐字编辑.
        /// </summary>
        public static string Nav_WordEdit {
            get {
                return ResourceManager.GetString("Nav_WordEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 字段.
        /// </summary>
        public static string SongInfo_Param {
            get {
                return ResourceManager.GetString("SongInfo_Param", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        public static string SongInfo_Value {
            get {
                return ResourceManager.GetString("SongInfo_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 颜色代码 (不带 #).
        /// </summary>
        public static string StyleEdit_Style_Color {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 非聚焦时隐藏.
        /// </summary>
        public static string StyleEdit_Style_Hidden {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Hidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 样式 ID.
        /// </summary>
        public static string StyleEdit_Style_Id {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位置.
        /// </summary>
        public static string StyleEdit_Style_Position {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居中.
        /// </summary>
        public static string StyleEdit_Style_Position_Center {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居左.
        /// </summary>
        public static string StyleEdit_Style_Position_Left {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 居右.
        /// </summary>
        public static string StyleEdit_Style_Position_Right {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 未定.
        /// </summary>
        public static string StyleEdit_Style_Position_Undefined {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Position_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览:.
        /// </summary>
        public static string StyleEdit_Style_Preview {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 类型.
        /// </summary>
        public static string StyleEdit_Style_Type {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 背景音.
        /// </summary>
        public static string StyleEdit_Style_Type_Background {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 正常.
        /// </summary>
        public static string StyleEdit_Style_Type_Normal {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 加重.
        /// </summary>
        public static string StyleEdit_Style_Type_Stressed {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Stressed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 轻声.
        /// </summary>
        public static string StyleEdit_Style_Type_Whisper {
            get {
                return ResourceManager.GetString("StyleEdit_Style_Type_Whisper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌词信息.
        /// </summary>
        public static string Title_LyricInfo {
            get {
                return ResourceManager.GetString("Title_LyricInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 歌曲信息 (Enter 新建行, Delete 删除行).
        /// </summary>
        public static string Title_SongInfo {
            get {
                return ResourceManager.GetString("Title_SongInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 预览模式.
        /// </summary>
        public static string Toggle_SongLines_PreviewMode {
            get {
                return ResourceManager.GetString("Toggle_SongLines_PreviewMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此行为伴奏.
        /// </summary>
        public static string WordEdit_LyricLine_Hint_Empty {
            get {
                return ResourceManager.GetString("WordEdit_LyricLine_Hint_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 此行为纯文本.
        /// </summary>
        public static string WordEdit_LyricLine_Hint_PureText {
            get {
                return ResourceManager.GetString("WordEdit_LyricLine_Hint_PureText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 选择下面的一行:.
        /// </summary>
        public static string WordEdit_LyricLines_Hint {
            get {
                return ResourceManager.GetString("WordEdit_LyricLines_Hint", resourceCulture);
            }
        }
    }
}
